stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install
        npm run build
- name: Docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: localhost:5001/sentiment-analysis-frontend:runcher
      registry: 127.0.0.1:34783
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: LoadBalancer
  steps:
  - applyYamlConfig:
      path: ./deployment-lb.yaml
timeout: 60
notification: {}
