apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/ingressState: '{"ZnJvbnRlbmQvc2EveGlwLmlvLy8vODA=":"deployment:sa:sentiment-analysis-frontend"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.103"],"port":80,"protocol":"HTTP","serviceName":"sa:ingress-717af44d09105b129e2f5502b8737a9e","ingressName":"sa:frontend","hostname":"frontend.sa.192.168.1.103.xip.io","path":"/","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"labels":{"cattle.io/creator":"norman"},"name":"frontend","namespace":"sa"},"spec":{"rules":[{"host":"xip.io","http":{"paths":[{"backend":{"serviceName":"ingress-717af44d09105b129e2f5502b8737a9e","servicePort":80},"path":"/"}]}}]},"status":{"loadBalancer":{}}}'
  labels:
    cattle.io/creator: norman
  name: frontend
  namespace: sa
spec:
  rules:
  - host: frontend.sa.192.168.1.103.xip.io
    http:
      paths:
      - backend:
          serviceName: ingress-717af44d09105b129e2f5502b8737a9e
          servicePort: 80
        path: /
status:
  loadBalancer: {}